services:
  web:
    container_name: obsidian-web
    build: .
    restart: always
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn obsidiantime.config.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "
    networks:
      - coolify

networks:
  coolify:
    external: true
