# Generated by Django 5.2.4 on 2025-07-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='rickroll_video_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rickroll_video',
            field=models.FileField(blank=True, help_text='Загрузите видео файл (MP4, WebM, OGG)', null=True, upload_to='videos/', verbose_name='Видео для рикролла'),
        ),
    ]
