# Generated by Django 5.2.4 on 2025-07-21 16:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_internal', models.BooleanField(default=False, help_text='Если отмечено, комментарий виден только администраторам', verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.feedback', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Комментарий к обращению',
                'verbose_name_plural': 'Комментарии к обращениям',
                'ordering': ['created_at'],
            },
        ),
    ]
