# Generated by Django 5.2.4 on 2025-07-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_feedbackcomment_admin_feedbackcomment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_notes',
        ),
    ]
