# Generated by Django 5.2.4 on 2025-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sociallink_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('vk', 'VKontakte'), ('donationalerts', 'DonationAlerts'), ('boosty', 'Boosty'), ('other', 'Другое')], max_length=20, verbose_name='Платформа'),
        ),
    ]
